# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: ko-KR

# Change to your timezone › https://zones.arilyn.cc
timezone: Asia/Seoul

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Sowon's CS Note
# the main title

tagline: Computer Science Study Log # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  컴퓨터공학 전공지식과 프로젝트를 기록하는 공간

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://wanimetro.github.io"

github:
  username: wanimetro # change to your GitHub username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: SOWON OH
  email: sowon0507@khu.ac.kr # change to your email address
  fediverse_handle: # fill in your fediverse handle. E.g. "@username@domain.com"
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/wanimetro # change to your GitHub homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

theme_mode:

cdn:

avatar: /assets/img/avatar.png

social_preview_image:

toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

baseurl: ""